### ISSUE TITLE
Water Elemental has an enrage, should also automatically have Water Bolt selected on summon

### ISSUE THREAD

**Issue by Tixlenra** [Blumfield/OregonCore#10]
**Current behavior**: 
Water Elemental somehow has an enrage; as-well as this, the Water Elemental casts Water Bolt but doesn't have it 'activated' on the UI when summoning.

**Expected behavior**: 
The Water Elemental should not enrage; should have Water Bolt activated on the UI.

**Steps to reproduce the problem**:
Summon Water Elemental, kill a few things, observe.

**Comment by Blumfield** [comment]
Fixed the water bolt and others pets too

**Comment by Tixlenra** [comment]
Closed because enrage cannot be reproduced.
